image: golang:latest

stages:
  - go

format:
  stage: go
  script:
    - go fmt .
    - go vet .

test:
  stage: go
  before_script:
    - go get .
    - go get -tool github.com/jstemmer/go-junit-report/v2@latest
  script:
    - go test ./... -json 2>&1 | go tool go-junit-report -parser gojson > report.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml

lint:
  stage: go
  before_script:
    - go get .
    - go get -tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
  script:
    - go tool golangci-lint run

build:
  stage: go
  script:
    - go get .
    - go build -o bin .
  artifacts:
    expire_in: 1 week
    paths:
      - bin